"""Write BOP-format scenes and models (used to build the committed mini fixture, D16).

Files follow the BOP layout read by :class:`binposert.data.BopDataset`. Output is deterministic for
identical inputs so the fixture can be regenerated byte-identically.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import imageio.v3 as iio
import numpy as np
import numpy.typing as npt
import trimesh

from binposert.transforms import Mat4, invert
from binposert.types import Mat3, ObjectModel

DEPTH_SCALE = 0.1  # mm per uint16 unit, as in T-LESS


def write_models(
    root: str | Path, models: list[ObjectModel], models_info: dict[str, dict[str, Any]]
) -> None:
    """Write ``models/obj_XXXXXX.ply`` (binary PLY) and ``models/models_info.json``."""
    models_dir = Path(root) / "models"
    models_dir.mkdir(parents=True, exist_ok=True)
    for m in models:
        mesh = trimesh.Trimesh(vertices=m.vertices, faces=m.faces, process=False)
        mesh.export(models_dir / f"obj_{m.object_id:06d}.ply")
    with open(models_dir / "models_info.json", "w") as f:
        json.dump(models_info, f)


def _bbox_xywh(mask: npt.NDArray[np.bool_]) -> list[int]:
    ys, xs = np.nonzero(mask)
    if len(xs) == 0:
        return [0, 0, 0, 0]
    return [
        int(xs.min()),
        int(ys.min()),
        int(xs.max() - xs.min() + 1),
        int(ys.max() - ys.min() + 1),
    ]


class BopSceneWriter:
    """Accumulate Views of one scene, then write the three scene JSON files."""

    def __init__(self, root: str | Path, split: str, scene_id: int) -> None:
        self.scene_dir = Path(root) / split / f"{scene_id:06d}"
        for sub in ("rgb", "depth", "mask", "mask_visib"):
            (self.scene_dir / sub).mkdir(parents=True, exist_ok=True)
        self.scene_camera: dict[str, Any] = {}
        self.scene_gt: dict[str, Any] = {}
        self.scene_gt_info: dict[str, Any] = {}

    def add_view(
        self,
        image_id: int,
        K: Mat3,
        T_world_camera: Mat4,
        rgb: npt.NDArray[np.uint8],
        depth_mm: npt.NDArray[np.float64],
        objects: list[tuple[int, Mat4]],
        masks_full: list[npt.NDArray[np.bool_]],
        masks_visible: list[npt.NDArray[np.bool_]],
    ) -> None:
        """``objects[i] = (object_id, T_camera_object)`` with matching full / visible masks."""
        key = str(image_id)
        T_camera_world = invert(T_world_camera)
        self.scene_camera[key] = {
            "cam_K": np.asarray(K, dtype=np.float64).ravel().tolist(),
            "depth_scale": DEPTH_SCALE,
            "cam_R_w2c": T_camera_world[:3, :3].ravel().tolist(),
            "cam_t_w2c": T_camera_world[:3, 3].tolist(),
        }
        iio.imwrite(self.scene_dir / "rgb" / f"{image_id:06d}.png", np.asarray(rgb, dtype=np.uint8))
        depth_u16 = np.round(np.asarray(depth_mm, dtype=np.float64) / DEPTH_SCALE).astype(np.uint16)
        iio.imwrite(self.scene_dir / "depth" / f"{image_id:06d}.png", depth_u16)

        valid_depth = depth_u16 > 0
        gts: list[dict[str, Any]] = []
        infos: list[dict[str, Any]] = []
        for i, ((object_id, T_camera_object), full, vis) in enumerate(
            zip(objects, masks_full, masks_visible, strict=True)
        ):
            iio.imwrite(
                self.scene_dir / "mask" / f"{image_id:06d}_{i:06d}.png", full.astype(np.uint8) * 255
            )
            iio.imwrite(
                self.scene_dir / "mask_visib" / f"{image_id:06d}_{i:06d}.png",
                vis.astype(np.uint8) * 255,
            )
            gts.append(
                {
                    "cam_R_m2c": T_camera_object[:3, :3].ravel().tolist(),
                    "cam_t_m2c": T_camera_object[:3, 3].tolist(),
                    "obj_id": int(object_id),
                }
            )
            px_all = int(full.sum())
            px_valid = int((full & valid_depth).sum())
            px_visib = int(vis.sum())
            infos.append(
                {
                    "bbox_obj": _bbox_xywh(full),
                    "bbox_visib": _bbox_xywh(vis),
                    "px_count_all": px_all,
                    "px_count_valid": px_valid,
                    "px_count_visib": px_visib,
                    "visib_fract": float(px_visib / px_valid) if px_valid > 0 else 0.0,
                }
            )
        self.scene_gt[key] = gts
        self.scene_gt_info[key] = infos

    def finish(self) -> None:
        for name, obj in (
            ("scene_camera", self.scene_camera),
            ("scene_gt", self.scene_gt),
            ("scene_gt_info", self.scene_gt_info),
        ):
            with open(self.scene_dir / f"{name}.json", "w") as f:
                json.dump(obj, f)
